import { Category } from "./category.types";
import { ObjectId } from "./common.types";
import { CompanyProfile, CompanyStaff } from "./company.types";
import { Profile } from "./profile.types";
export interface JobPost {
  _id: ObjectId;
  companyId: CompanyProfile;
  title: string;
  location: string;
  jobType: "full-time" | "part-time" | "contract" | "internship" | "remote";
  description: string;
  salaryFrom: number;
  salaryTo: number;
  salaryCurrency: string;
  benefits?: string[];
  category?: Category | ObjectId;
  skills?: string[];
  status?: "open" | "closed" | "draft";
  deadline?: Date;
  requirements?: string[];
  contacterId: CompanyStaff | ObjectId;
  contacterEmail: string;
  profile?: Profile;
  keyResponsibilities?: string[];
  applications: Profile[];
  experienceLevel?: "Entry" | "Mid" | "Senior" | "Executive";
  other?: { title?: string; description?: string; [key: string]: unknown };
  viewCount: number;
  applicationCount: number;
  isFeatured: boolean;
  slug: string;
  createdAt: Date;
  updatedAt: Date;
}
